"""
This file supports safety classification and categorization with QwenGuard3 over each prompt,
in order to verify ability dimensions
"""
import pandas as pd 
from transformers import AutoModelForCausalLM, AutoTokenizer
import re
import matplotlib.pyplot as plt
model_name = "Qwen/Qwen3Guard-Gen-8B"
from scipy.stats import pearsonr
import numpy as np

# Benchmarks in report order: general reasoning first, then safety
benchmark_order = [
    "bbh", "gpqa", "ifeval", "math", "mmlu-pro", "musr",           # reasoning
    "bbq", "do_anything_now", "harmbench", "trustllm_jailbreaktrigger", "strongreject", "toxigen", "wildguardtest", "wildjailbreak",  # safety
    "wmdp", "xstest",
]

benchmark_rename = {
    "bbh": "BBH", "gpqa": "GPQA", "mmlu-pro": "MMLU-Pro", "math": "MATH", "musr": "MuSR", "ifeval": "IFEval",          # reasoning
    "harmbench": "HarmBench", "strongreject": "StrongReject", "wildjailbreak": "WildJailbreak", "wildguardtest": "WildGuardTest",  # safety
    "do_anything_now": "Do-Anything-Now", "trustllm_jailbreaktrigger": "JailbreakTrigger", "toxigen": "ToxiGen",
    "bbq": "BBQ", "wmdp": "WMDP", "xstest": "XSTest",
}

def order_and_rename_benchmarks(df):
    """
    Sort a benchmark-indexed frame into benchmark_order and swap the raw
    benchmark keys for their display names. Benchmarks missing from
    BENCHMARK_ORDER keep their relative order and are appended at the end.
    Returns the frame untouched if it is not indexed by raw benchmark names
    (e.g. it has already been renamed), so it is safe to call twice.

    Inputs: 
        df | pd.DataFrame: The dataframe to reindex
    Outputs:
        The reindexed dataframe
    """
    known = [b for b in benchmark_order if b in df.index]
    if not known:
        return df
    rest = [b for b in df.index if b not in benchmark_order]
    return df.loc[known + rest].rename(index=benchmark_rename)


# From the Qwen3Guard HuggingFace Repository
def extract_label_and_categories(content):
    """
    Extract the labels generated by QwenGuard
    Inputs:
        content | str: The response from the model
    Outputs:
        label | str: Whether the input was deemed safe, unsafe, or controversial
        categories | list: Any category that the prompt was given
    """
    safe_pattern = r"Safety: (Safe|Unsafe|Controversial)"
    category_pattern = r"(Violent|Non-violent Illegal Acts|Sexual Content or Sexual Acts|PII|Suicide & Self-Harm|Unethical Acts|Politically Sensitive Topics|Copyright Violation|Jailbreak|None)"
    safe_label_match = re.search(safe_pattern, content)
    label = safe_label_match.group(1) if safe_label_match else None
    categories = re.findall(category_pattern, content)
    return label, categories

def run_classification(data, output_dir):
    """
    Evaluate all prompts in the data and map them to safety classifications and categories
    Inputs:
        data | str: The filename of the csv containing item_statistics file generated from a two dimensional IRT run
        output_dir | str: The folder to save the results in
    Outputs:
        A csv file with all safety classifications and categories saved per prompt
        Prints the correlation to the IRT dimensions
    """
    questions = pd.read_csv(data)

    # load the tokenizer and the model
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype="auto",device_map="auto")

    # prepare the model input
    prompts = []
    ids = []
    for i, row in questions.iterrows():
        prompts.append(row["question_text"])
        ids.append(row["question_id"])

    messages = [{"role": "user", "content": p} for p in prompts]

    results = []

    for i in range(len(messages)):
        if i % 100 == 0:
            print(i)
        m = messages[i]
        q_i = ids[i]
        p = prompts[i]
        text = tokenizer.apply_chat_template(
            [m],
            tokenize=False
        )
        model_inputs = tokenizer([text], return_tensors="pt").to(model.device)

        # conduct text completion
        generated_ids = model.generate(
            **model_inputs,
            max_new_tokens=128
        )
        output_ids = generated_ids[0][len(model_inputs.input_ids[0]):].tolist() 

        content = tokenizer.decode(output_ids, skip_special_tokens=True)
        safe_label, categories = extract_label_and_categories(content)
        results.append({
            "question_id": q_i,
            "prompt": p,
            "message": m,
            "safe_label": safe_label,
            "categories": categories
        })

    r = pd.DataFrame(results)
    r.to_csv(f"{output_dir}safety_label.csv")

    q_final = questions.merge(r, on="question_id")

    q_final.to_csv(f"{output_dir}item_statistics_0_safety_label.csv")

    mapping = {
        "Safe": -1,
        "Controversial": 0,
        "Unsafe": 1
    }
    q_final["category_num"] = q_final["safe_label"].map(mapping)
    
    disc_0, p_disc_0 = pearsonr(q_final["category_num"],q_final["Discrimination 0"])
    disc_1, p_disc_1  = pearsonr(q_final["category_num"],q_final["Discrimination 1"])
    diff_0 , p_diff_0 = pearsonr(q_final["category_num"],q_final["Difficulty 0"])
    diff_1, p_diff_1 = pearsonr(q_final["category_num"],q_final["Difficulty 1"])

    print("Discrimination 0", disc_0, p_disc_0)
    print("Difficulty 1", diff_1, p_diff_1)
    print("Difficulty 0", diff_0, p_diff_0)
    print("Discrimination 1", disc_1, p_disc_1)


def graph_stacked_columns_classification(df, bin_name, output_dir, disc_0_label = "Safety", disc_1_label = "General Reasoning"):
    """
    Graph safety classification for display
    Inputs:
        df | pd.DataFrame: DataFrame with safety classification per prompt
        bin_name | str: The column to group on
        output_dir | str: The folder to save the resulting graphs to
        disc_0_label | str: The label to associate with dimension 0
        disc_1_label | str: The label to associate with dimension 1
    Outputs:
        Saves the specified graph to the output_dir

    """
    if bin_name == "benchmark":
        df = order_and_rename_benchmarks(df)

    x = df.index.astype(str)

    safe = df["Safe"]
    controversial = df["Controversial"]
    unsafe = df["Unsafe"]

    plt.rcParams.update({
        "font.size": 12,
        "axes.labelsize": 13,
        "axes.titlesize": 14,
        "legend.fontsize": 11,
        "xtick.labelsize": 8,
        "ytick.labelsize": 11,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "figure.dpi": 300,
    })

    COLORS = {
        "safe": "#0072B2",
        "controversial": "#F0E442",
        "unsafe": "#D55E00",
    }
    name_map = {
        "disc_0_bin": "Dimension 0 Discrimination " + disc_0_label,
        "disc_1_bin": "Dimension 1 Discrimination "+ disc_1_label,
        "diff_0_bin": "Dimension 0 Difficulty "+ disc_0_label,
        "diff_1_bin": "Dimension 1 Difficulty "+ disc_1_label,
        "benchmark": "Benchmark"
    }

    nice_bin_name = name_map.get(bin_name, bin_name)

    fig, ax = plt.subplots(figsize=(8.5, 5.5))

    width = 0.72
    # width = 0

    # Stacked bars
    b1 = ax.bar(
        x,
        safe,
        width=width,
        color=COLORS["safe"],
        label="Safe",
        linewidth=0.6,
        edgecolor="white"
    )

    b2 = ax.bar(
        x,
        controversial,
        width=width,
        bottom=safe,
        color=COLORS["controversial"],
        label="Controversial",
        linewidth=0.6,
        edgecolor="white"
    )

    b3 = ax.bar(
        x,
        unsafe,
        width=width,
        bottom=safe + controversial,
        color=COLORS["unsafe"],
        label="Unsafe",
        linewidth=0.6,
        edgecolor="white"
    )

    ax.set_ylabel("Percent of Prompts")
    ax.set_xlabel(nice_bin_name)

    ax.set_ylim(0, 100)

    # Light horizontal grid
    ax.grid(
        axis="y",
        linestyle="--",
        linewidth=0.5,
        alpha=0.4
    )

    ax.set_axisbelow(True)

    # Legend at top center
    ax.legend(
        loc="upper center",
        bbox_to_anchor=(0.5, 1.12),
        ncol=3,
        frameon=False
    )

    # Clean ticks
    if bin_name == "benchmark":
        plt.xticks(rotation=20, ha="right")
    else: 
        step = 5

        tick_positions = np.arange(len(x))[::step]
        tick_labels = x[::step]

        ax.set_xticks(tick_positions)
        ax.set_xticklabels(tick_labels, rotation=20, ha="right")

    # Tight layout for papers
    plt.tight_layout(pad=0.8)

    plt.savefig(
        f"{output_dir}{bin_name}.png",
        dpi=400,
        bbox_inches="tight"
    )
    plt.close()


def graph_stacked_columns_category(df, bin_name, output_dir, disc_0_label = "Safety", disc_1_label = "General Reasoning"):
    """
    Graph safety categories for display
    Inputs:
        df | pd.DataFrame: DataFrame with safety classification per prompt
        bin_name | str: The column to group on
        output_dir | str: The folder to save the resulting graphs to
        disc_0_label | str: The label to associate with dimension 0
        disc_1_label | str: The label to associate with dimension 1
    Outputs:
        Saves the specified graph to the output_dir
    """
    df = df.rename(columns={
        "['Copyright Violation']": "Copyright Violation",
        "['Jailbreak']": "Jailbreak",
        "['Non-violent Illegal Acts']": "Non-violent Illegal Acts",
        "['None']": "None",
        "['PII']": "PII",
        "['Politically Sensitive Topics']": "Politically Sensitive Topics",
        "['Sexual Content or Sexual Acts']": "Sexual Content or Sexual Acts",
        "['Suicide & Self-Harm']": "Suicide & Self-Harm",
        "['Unethical Acts']": "Unethical Acts",
        "['Violent']": "Violent"
    })

    if bin_name == "benchmark":
        df = order_and_rename_benchmarks(df)

    x = df.index.astype(str)

    categories = [
        "None",
        "Copyright Violation",
        "Jailbreak",
        "Non-violent Illegal Acts",
        "PII",
        "Politically Sensitive Topics",
        "Sexual Content or Sexual Acts",
        "Suicide & Self-Harm",
        "Unethical Acts",
        "Violent"
    ]

    colors = {
        "None": "#0072B2",
        "Copyright Violation": "#D55E00",
        "Jailbreak": "#CC79A7",
        "Non-violent Illegal Acts": "#000000",
        "PII": "#E69F00",
        "Politically Sensitive Topics": "#56B4E9",
        "Sexual Content or Sexual Acts": "#009E73",
        "Suicide & Self-Harm": "#F0E442",
        "Unethical Acts": "#595959",
        "Violent": "#A0A0A0"
    }

    plt.rcParams.update({
        "font.size": 12,
        "axes.labelsize": 13,
        "legend.fontsize": 10,
        "xtick.labelsize": 10,
        "ytick.labelsize": 10,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "figure.dpi": 300,
    })

    name_map = {
        "disc_0_bin": "Dimension 0 Discrimination " + disc_0_label,
        "disc_1_bin": "Dimension 1 Discrimination "+ disc_1_label,
        "diff_0_bin": "Dimension 0 Difficulty "+ disc_0_label,
        "diff_1_bin": "Dimension 1 Difficulty "+ disc_1_label,
        "benchmark": "Benchmark"
    }

    nice_bin_name = name_map.get(bin_name, bin_name)

    fig, ax = plt.subplots(figsize=(9, 5.8))

    bottom = np.zeros(len(df))
    width = 0.72

    for cat in categories:
        values = df[cat]

        bars = ax.bar(
            x,
            values,
            width=width,
            bottom=bottom,
            label=cat,
            color=colors[cat],
            edgecolor="white",
            linewidth=0.5
        )

        bottom += values

    ax.set_ylabel("Percent of Prompts")
    ax.set_xlabel(nice_bin_name)

    ax.set_ylim(0, 100)

    ax.grid(
        axis="y",
        linestyle="--",
        linewidth=0.5,
        alpha=0.35
    )

    ax.set_axisbelow(True)

    max_labels = 20
    step = max(1, len(x) // max_labels)

    tick_positions = np.arange(len(x))[::step]
    tick_labels = x[::step]

    ax.set_xticks(tick_positions)
    ax.set_xticklabels(tick_labels, rotation=20, ha="right")

    ax.legend(
        loc="upper center",
        bbox_to_anchor=(0.5, 1.3),
        ncol=3,
        frameon=False,
        columnspacing=1.2,
        handlelength=1.5
    )

    plt.tight_layout(pad=0.8)
    plt.subplots_adjust(top=0.80)


    plt.savefig(
        f"{output_dir}{bin_name}_category.png",
        dpi=400,
        bbox_inches="tight"
    )
    plt.close()
    

def analyze_classification(data, output_dir, disc_0_label="Safety", disc_1_label="General Reasoning"):
    """
    Create the graphs analyzing the splits
    Inputs:
        data | str: The filename of the csv containing the classification data
        output_dir | str: The folder to save the graphs in
        disc_0_label | str: The label to associate with dimension 0
        disc_1_label | str: The label to associate with dimension 1
    Outputs:
        Graphs for each bin type for both classification and category
    """

    q = pd.read_csv(data)
    # Create the bins
    q['disc_0_bin'] = pd.qcut(q['Discrimination 0'], 100, labels=False)
    q['disc_1_bin'] = pd.qcut(q['Discrimination 1'], 100, labels=False)
    q['diff_0_bin'] = pd.qcut(q['Difficulty 0'], 100, labels=False)
    q['diff_1_bin'] = pd.qcut(q['Difficulty 1'], 100, labels=False)

    categorical_cols = ["disc_0_bin", "disc_1_bin", "diff_0_bin", "diff_1_bin", "benchmark"]

    result = {}

    # Create the safety classification label graphs
    for col in categorical_cols:
        percent = (
            q.groupby(col)["safe_label"]
            .value_counts(normalize=True)
            .unstack(fill_value=0)
            * 100
        )
        if col == "benchmark":
            percent = order_and_rename_benchmarks(percent)
        percent.to_csv(f"{output_dir}{col}.csv")
        graph_stacked_columns_classification(percent, col, output_dir, disc_0_label, disc_1_label)

    # Create the safety category label graphs
    for col in categorical_cols:
        percent = (
            q.groupby(col)["categories"]
            .value_counts(normalize=True)
            .unstack(fill_value=0)
            * 100
        )
        if col == "benchmark":
            percent = order_and_rename_benchmarks(percent)
        percent.to_csv(f"{output_dir}{col}_categories.csv")
        graph_stacked_columns_category(percent, col, output_dir, disc_0_label, disc_1_label)
